Scribes on k-means
nakverma/uml-notes pull request #29
Opened 2020-02-18 19:55 UTC by huberf

The PR should contain all needed additions for the Scribe task, but we did have a question which we wanted your input on before we committed:
As the k-means topic coverage spans multiple sections, we kept our additions in two separate files. Which sections (if any) do you all suggest we put our additions into?
In line with this, is it right that our additions should be marked by a `\subsection` rather than a `\section`?

Thanks!

2020-02-23 23:27 UTC, all2187 requested changes
For the sections, how about you move the two hardness of kmeans results into the relevant section (section 5). Then make a new section after the heuristics section for the approximation result (since you refer to Lloyd's method). Or make it the section before heuristics (this may make more sense) but remove references to Lloyd's method. Do whichever makes more sense to you. Also if you could add a few lines about why people use heuristics (lloyd's, kmeans++, etc) in practice even though a 1+epsilon approximation is possible, that would be great.

I've made a number of smaller comments on the PR as well. Let me know if you have any questions.

Overall though, great job!

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +\subsection{(1+$\epsilon$)-approximate $k$-means clustering}
This should be \section{}

2020-02-23 23:27 UTC, all2187 commented on chapter_1/chapter_1.tex
> +  \input{chapter_1/kmeans_hardness_d2_k2}
Remove this and move to the section 5 file.

2020-02-23 23:27 UTC, all2187 commented on chapter_1/chapter_1.tex
> +  \input{chapter_1/kmeans_1pluseps_approx}
Prepend with 7 or 6 or whatever section number it ends up being, edit other section numbers as needed.

2020-02-23 23:27 UTC, all2187 commented on chapter_1/chapter_1.tex
>    \input{chapter_1/further_reading}
Could you prepend the section number here too while you are at it (and modify the file name as needed).

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +\section{Hardness of $k$-means when $k=2$}
Make it subsection

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +\section{Hardness of $k$-means when $d=2$}
Make it subsection

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +\subsection{Setup}
Just make it a nice texbf heading, no need to make it a section/subsection that appears in the ToC

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +\subsection{Overview}
Just make it a nice texbf heading, no need to make it a section/subsection that appears in the ToC

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +\subsection{Walking through the proof}
Just make it a nice texbf heading, no need to make it a section/subsection that appears in the ToC

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +We will prove that $k$-means is NP-hard when $k=2$. There is a simple proof by (CITE) that is a reduction from densest cut. Densest cut is equivalent to sparsest cut on the complement graph, which is
You are showing it is NP-hard EVEN when k=2. You've already showed it NP hard in class.

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +We will prove that $k$-means is NP-hard when $k=2$. There is a simple proof by (CITE) that is a reduction from densest cut. Densest cut is equivalent to sparsest cut on the complement graph, which is
Forgot to add the citations

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +    For a given graph $G=(V,E)$, find a bipartition $(P,Q)$ of the vertices in $G$ that maximizes $|E(P,Q)/(|P||Q|)$, where $E(P,Q)$ denotes the edge set of the cut.
Missing cardinality bar. Use \abs{} macro instead.

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +Run $k$-means with $k=2$ on the set of points corresponding to the rows in $M$, of dimension $|E|$. Note that each point represents a vertex in $G$. Given an optimal solution to this $k$-means instan
Specify that each point has dim |E| (i read it as there are |E| points).

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +So Equation 1 corresponds to the form given in the paper, i.e.
What equation 1? Use \label and \eqref if trying to refer to an equation you wrote

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +\begin{align}
Here i'm a bit confused, is the cost you are mentioning the same cost as above (kmeans cost) or are you computing the densest cut cost?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +Minimizing this cost is equivalent to maximizing the densest cut objective $|E(P,Q)|/(|P||Q|)$.\qed
Something here isn't clear, i was following until my last comment, but it is unclear what cost you are computing, what "form given in the paper" you are referring to, or how the computer cost here shows what you wanted to show. More details have to be given. Why was it important that the total cost was (1-1/p)^2+(1-1/q)^2 before?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +We will prove that $k$-means is NP-hard when $d=2$ and $k=\Theta(n^\epsilon)$ for $\epsilon>0$. We'll try to provide some intuition around the proof structure as well as a summary of the results pres
Same as before, i think the word "even" is important. Might want to mention why in previous section or this one. Also you left the (CITE)

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +The reduction will be from Exact Cover by 3-Sets (X3C), which is known to be NP-complete (CITE).\\
CITE

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +The $k$-means clustering problem is NP-hard for $k=\Theta(n^\gamma)$ for some $0<\gamma<1$.
For d=2 no?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +    Suppose Theorem 1 is true. Then the $k$-means clustering problem is also NP-hard for $k=\Theta(n^\epsilon)$ for any $\epsilon>0$.
Note theorem 1, theorem 1.8.3 or whatever, use ref and label

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +We reproduce the proof almost verbatim from the paper. Fix $\epsilon>0$, and take a hard instance with $n$ points and $k$ centers, with $k=\Theta(n^\gamma)$ as in Theorem 1.
ditto as above

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +
What about gamma=epsilon?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +Definition 5 allows us to see where the number of clusters $k=l(3n+2)+(l-1)3n$ comes from. A nice clustering corresponds naturally to this $k$, since there are $l-1$ $M$ rows, each with $3n$ points i
Where are def 4 and lemma 6 discussed?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +Now we will present the paper's proof of Theorem 1. Instead of re-typing everything, we will instead try to expand on explanations and provide some more intuition, and refer the reader to the paper f
This whole section is a bit hard to read without having read the paper before hand. Giving a summary/intuition and omitting technical details is totally fine (and ideal). It makes sense to refer readers to the paper for technical details. However, try to make the intuition/summary self contained. Here i dont know what definitions 4 and lemma 6 are. Nor do i know precisely what lemma 7 is, etc. The "let's read up until" comments make this more of a reading along guide than a self contained summary. Try to edit it a bit to make it closer to the latter (although again referring readers to the paper for technical details is what we want to do).

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_hardness_d2_k2.tex
> +$(\implies)$ Suppose we have an optimal $k$-clustering with cost $\le L$. The
Is this the proof of lemma 11? If so put it in \begin{proof} environment or just state you will now prove lemma 11. It's a little unclear as is.

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +Let $X \subset \bbR^d$ be an n-point set, and let $\epsilon >0$ be given. A (1 + $\epsilon$)-approximately optimal 2-clustering of X can be found in time $O(n\text{ log }n \cdot \epsilon^{-2d} \text{
Use \R instead of \bbR

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +Let $X \subset \bbR^d$ be an n-point set, and let $\epsilon >0$ be given. A (1 + $\epsilon$)-approximately optimal 2-clustering of X can be found in time $O(n\text{ log }n \cdot \epsilon^{-2d} \text{
Use \log

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +Let $X \subset \bbR^d$ be an n-point set, and let $\epsilon >0$ be given. A (1 + $\epsilon$)-approximately optimal 2-clustering of X can be found in time $O(n\text{ log }n \cdot \epsilon^{-2d} \text{
Do this throughout (many occurences below)

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +Let $\epsilon \geq 0$. We define $\sim_{\epsilon}$ to be a relation on ordered pairs of points in $\bbR^d$. We say that $(x,y)$ and $(x',y')$ are $\epsilon$-near if $(x,y) \sim_{\epsilon} (x', y')$ s
Use \norm{} macro throughout

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +\noindent \emph{Approximate range searching}. An important and useful concept for optimizing this problem is approximate range searching. At a high level, this method uses intelligent preprocessing t
weight**ed** sum?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +\noindent \emph{Putting the points on a polynomial-size grid}. The proposed k-clustering problem works with points with polynomially large distances between them, however ratios of interpoint distanc
For quotaions in latex use ` and '

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +\noindent \emph{Putting the points on a polynomial-size grid}. The proposed k-clustering problem works with points with polynomially large distances between them, however ratios of interpoint distanc
\log not log

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +Let $S$ be a finite set in $\bbR^d$. The quadratic-mean radius of S is
$S$ not S

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +be the \emph{quadratic-mean radius} of S. For a real number $\epsilon \geq 0$, the \emph{$\epsilon$-tolerance ball} of S is the ball centered as $c(S)$ of radius $(\epsilon/3)\rho(S)$.
Ditto as previous

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +    \caption{(a) The set $C_Q$ and (b) the subdivision of $Q$}
You should cite the source of this figure

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +    \caption{(a) The set $C_Q$ and (b) the subdivision of $Q$}
See how it is done in other parts

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +It remains to show that this algorithm can be performed in near-linear time. In a direct implementation of this algorithm, we must consider $|C|^2$ pairs $(c_1,c_2)$ and for each pair, we need $O(n)$
Why does that imply O(n^2) for fixed epsilon?

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +The full k-clustering algorithm builds on the intuition of the 2-clustering version and employs a recursive approach for finding the $(1+\epsilon)$ approximate.
apprxoimate what? There is a word missing or something at the end of this sentence

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +\textbf{The proof of running time for this method builds on the proof for approximate $2$-clustering and employs the recursive nature of the algorithm to go from $O(n \log n)$ for 2-clustering to $O(
Why is this bold? Remark already italicizes it

2020-02-23 23:27 UTC, all2187 commented on chapter_1/kmeans_1pluseps_approx.tex
> +% Contributers: Noah Huber-Feely, Samuel Sharpe
Overall, you did a great job in this section. However, you may want to consider breaking this section into 2 or three subsections. Maybe 1 subsection for preliminary definitions, one for the 2means result, and one for kmeans. Also try to add some intuitive explanations of the algorithms for 2means and kmeans.

2020-02-29 21:03 UTC, all2187 commented
I see there are some new commits, just let me know when it is ready to rereview.

2020-03-02 23:12 UTC, huberf commented
@all2187 We have now added all the requested formatting changes and content additions. Let us know if there is anything more or we did something in a different way than you want. Thanks!

2020-03-08 22:06 UTC, all2187 approved these changes
Looks great! Good job!

2020-03-08 22:06 UTC, merged