Chapter 3 Spectral Clustering
nakverma/uml-notes pull request #32
Opened 2020-03-18 07:39 UTC by tzm41

Sorry for the delay. It has also been quite hard for me to do this alone, when I don't have a teammate to discuss with. Frankly, the convergence paper is a bit hard for me to comprehend. Maybe my brain is already too fried to take in new theorem proofs.

Please let give me hints on how to parse Theorem 4 and 5 in that paper if possible!

2020-03-18 14:48 UTC, all2187 commented
Hi Colin. No worries, I understand (and the extraordinary circumstances around the virus can't have helped). I'll have a look in the next few days and let you know what I think / how to understand the theorems. 

Thank you for your hard work!

- Alex

2020-03-26 17:34 UTC, all2187 requested changes
Good job! There are a few minor typos and changes that you should make (see comments) but otherwise it looks great. Just make the changes and post a comment here when it is done and I will merge. 

Concerning Theorems 4 and 5, I think you discuss them in sufficient detail as is for our purposes. However, I'm happy to look at them in more detail and discuss them with you if you are interested. From a quick look, it seems to me that Theorem 4 is the relatively dry technical result that the paper makes use of. It seems to be along the lines of: given arcane assumptions on a function class G, the dot product (so some similarity measure) between functions f and these G functions computed from samples converges to the true dot product. More importantly this happens unformly for all functions in G (and f?). Theorem 5 applies this to the spectral clustering case to get that the sample eigenfunction converges to the true eigenfunction. At least that's what it seems like from a quick look... Let me know if you want to discuss this further, independently from these scribes.

2020-03-26 17:34 UTC, all2187 commented on chapter_3/2_spectral_clustering.tex
> +	They relate the operators $T_n$ defined on $L_2 (P_n)$, to some operators $S_n$ on the space $L_2 (P)$ such that their spectra are preserved, so that it could be used as a middle ground to prove $T_
There's a weird character here "deﬁned" (the f and i are a single character). It doesn't compile as a result. Fix this please.

2020-03-26 17:34 UTC, all2187 commented on chapter_3/2_spectral_clustering.tex
> +	\subsection{Review of Spectral Theory: Geometric \& the collection of all Borel sets on Characterization of Eigenvalues}
What does this mean?

2020-03-26 17:34 UTC, all2187 commented on chapter_3/2_spectral_clustering.tex
> +	\textbf{Input:} $S$: $n\times n$ similarity matrix (on $n$ datapoints), $k$: number of clusters.
Try to put this in a \begin{algorithm}\begin{algorithmic} environment if possible (see how its done elsewhere in the tex).

2020-03-26 17:34 UTC, all2187 commented on chapter_3/2_spectral_clustering.tex
> +	\begin{itemize}
Same, try to put in an algorithm env, just makes it easier to read.

2020-03-26 19:01 UTC, tzm41 commented on chapter_3/2_spectral_clustering.tex
> +	\subsection{Review of Spectral Theory: Geometric \& the collection of all Borel sets on Characterization of Eigenvalues}
Sorry, made an accidental edit

2020-03-27 06:40 UTC, tzm41 commented
@all2187 Comments addressed.

2020-04-06 16:56 UTC, all2187 approved these changes
Good job! Merging now.

2020-04-06 16:56 UTC, merged