Added topics of chapter 12 TDA
nakverma/uml-notes pull request #35
Opened 2020-05-01 01:20 UTC by EricaWei053

Added topics of chapter 12 TDA, written by Yixuan Li, Erica Wei and Ben Brimacombe.

2020-05-01 19:29 UTC, all2187 requested changes
Overall really great job! Thank you for having quite well covered the topic and looked at some extra papers. 

The main issue is that your .tex doesn't compile as is. I have identified the issues in my comments. There are also a few typos or minor changes to make. Finally, section 3 seems to be incomplete (there seem to be some leftover TODOs that you wrote to yourselves). Could you try to quickly fix these things and let me know when done. Ideally none of this should take too long so if you can quickly do it before Monday (05/04) that would be wonderful. If that isn't going to be possible, just let me know. Don't worry to much about section 3, just clean it up quickly so there aren't TODOs left in the text.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/2_Mapper_algorithm.tex
> +\SetAlgoLined
This uses the algorithm2e package which isnt used in the text. Please change to use the algorithmic package instead.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +Nerve Theorem tell that, for well-chosen values of r, η, the η-offsets of M are homotopy equivalent
Please do a ctrl-f to replace this η character by $\eta$. Otherwise it doesn't compile.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/4_ Persist_Homology.tex
> +%Contributor: Erica Wei
The file name has a space between 4_ and Persist which breaks compilation, please remove it.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/chapter_12.tex
> +\input{chapter_12/4_ Persist_Homology}
The file name has a space between 4_ and Persist which breaks compilation, please remove it.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/4_ Persist_Homology.tex
> +Let $\V$ be a persistence module indexed by T $\subset$ R. If T is a finite set or if all
\V is not a command and breaks compilation

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +’s. Under some regularity
typo? ('s)

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +’s. Under some regularity
has what?

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +2. From a practical and algorithmic perspective, topological features of M are inferred from
What is this 2.? This paragraph seems to have some typos in it which make it hard to understand.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/references.bib
> +@misc{chazal2017introduction,
Please cite/refer to these papers in the text by using the \cite command.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +Change:
Change what?

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +Change:
Was this a TODO you didn't remove?

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +The r-offset
The r-offset, what... I think you are missing something here.

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +Mention Isotopy Lemma Grove (1993)
Same

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +Change:
Same

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +Add citations to usefulness and different approaches.
Please do

2020-05-01 19:29 UTC, all2187 commented on chapter_12/3_Reconstruction.tex
> +pass
pass???

2020-05-01 19:29 UTC, all2187 commented on chapter_12/4_ Persist_Homology.tex
> +From Chazal et al., 2016a, Theorem 2.8, the results give some necessary conditions for a persistence module to be decomposable as a direct sum of interval modules.
cite using \cite

2020-05-01 19:29 UTC, all2187 commented on chapter_12/4_ Persist_Homology.tex
> +\begin{theorem}
Maybe explain why this theorem matters?

2020-05-01 19:29 UTC, all2187 commented on chapter_12/4_ Persist_Homology.tex
> +\section{Persist Homology}
Shouldn't it be persistent homology?

2020-05-01 19:29 UTC, all2187 commented on chapter_12/4_ Persist_Homology.tex
> +\subsection{Properties of Persist Homology}
Same, shouldn't it be Persistent Homology?

2020-05-03 05:04 UTC, EricaWei053 commented
Fixed typos and compilation errors.

2020-05-04 03:54 UTC, all2187 commented
Great job! Thank you for making the changes quickly.

2020-05-04 03:54 UTC, merged